<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $url= $storeManager->getStore()->getCurrentUrl(false);
   
$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$items = $cart->getQuote()->getAllItems();
if (false){
            error_log("checking items for qtylist");
            ob_start();
             var_dump($items);
            $result = ob_get_clean;
             error_log($result);
}
$helperData = $objectManager->get('\Altitude\SX\Helper\Data');
$availQtyStatus = $helperData->getConfigData('defaults/products/check_aval_qty');
$low_qty_amt = $helperData->getConfigData('defaults/products/low_qty_amt');
$low_qty_msg = $helperData->getConfigData('defaults/products/low_qty_msg');
$zero_qty_msg = $helperData->getConfigData('defaults/products/zero_qty_msg');
$full_qty_msg = $helperData->getConfigData('defaults/products/full_qty_msg');

$cart2 = $objectManager->get('Magento\Checkout\Model\Session');  
$defaultregionname = $cart2->getQuote()->getShippingAddress()->getRegion();

?>
<?php
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()):
?>
<div class="preloaded_addr" style="display:none">
    <?php
        $customerId = $customerSession->getCustomer()->getId();
        $customerObj = $objectManager->create('Magento\Customer\Model\Customer')->load($customerId);
        $customerAddress = array();
        foreach ($customerObj->getAddresses() as $address)
        {
            $customerAddress[] = $address->toArray();
        }
    ?>
    <?php foreach ($customerAddress as $customerAddres): ?>
            <?php 
            $regionname = $customerAddres['region']; 
            $regioncollect = $objectManager->create('Magento\Directory\Model\ResourceModel\Region\Collection')
                 ->addFieldToFilter('default_name', ['eq' => $regionname])->getFirstItem();
            $regiondata = $regioncollect->getData();
            if (isset($regiondata['code'])) {
                $region = $regiondata['code'];
            }
            ?>
            <div class="addr_region <?php if($defaultregionname == $regionname){ echo "customqty"; } ?>" data-region="<?= $regionname ?>">
<?php $i = 0; ?>
<?php
    $prodList = [];
   // foreach($items as $item){
        //$prodList[] = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId()); 
      //  error_log ("Calling getQtyInfo on line 50 of SXProducts/view/frontend/templates/qtycartcontent.phtml " . $url );
	//	$productQtyList = $helperData->getQtyInfoArray($items, $region);
   // } //foreach($productQtyList as $productQty): 
?>
<?php foreach($items as $item): ?>
    <div class="itemavailqty" itemposi="<?= $i ?>">
    <?php $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId()); ?>
    <?php
            //error_log ("Calling getQtyInfo on line 64 of SX/view/frontend/templates/qtycartcontent.phtml " . $url );
			$availQty = $helperData->getQtyInfo($_product, $region);
			$qtyAvailable = $availQty;
			$availQty = (!empty($availQty['qty'])) ? $availQty['qty'] : 0;
			$qtyData = $full_qty_msg;
			$message = $full_qty_msg;
			if($availQty <= 0){
				$message = $zero_qty_msg;
			}else if($availQty <= $low_qty_amt){
				$message = $low_qty_msg;
			}
    ?>
        <?php if (isset($qtyAvailable['qty']) && ($availQtyStatus == 0)): ?>
			<div class="details-qty addeditemqty" id="<?php echo "itemid-".$_product->getId() ?>">
                <span class="label"><strong><?= __('Qty Available') ?></strong></span>
                <div class="value"> <?php echo $qtyAvailable['qty'] ?></div>
            </div>
        <?php endif; ?>
		<?php if ($availQtyStatus == 1): ?>
			<div class="details-qty addeditemqty" id="<?php echo "itemid-".$_product->getId() ?>">
			<strong class="config-message"><?php echo  __($message) ?></strong>
			</div>
		<?php endif; ?>

    <?php $i++; ?>
    </div>
<?php endforeach; ?>
</div>
    <?php endforeach; ?>
</div>
<?php else: ?>
<div id="customqtycheckout" class="customqty" style="display:none;">
                <?php $i = 0; ?>
                <?php foreach($items as $item): ?>
                    <div class="itemavailqty" itemposi="<?= $i ?>">
                    <?php $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId()); ?>
                    <?php
            //error_log ("Calling getQtyInfo on line 83 of SXProducts/view/frontend/templates/qtycartcontent.phtml "  . $url );
			$availQty = $helperData->getQtyInfo($_product);
			$qtyAvailable = $availQty;
                			$availQty = (!empty($availQty['qty'])) ? $availQty['qty'] : 0;
                			$qtyData = $full_qty_msg;
                			$message = $full_qty_msg;
                			if($availQty <= 0){
                				$message = $zero_qty_msg;
                			}else if($availQty <= $low_qty_amt){
                				$message = $low_qty_msg;
                			}
                    ?>
                        <?php if (isset($qtyAvailable['qty']) && ($availQtyStatus == 0)): ?>
                			<div class="details-qty addeditemqty" id="<?php echo "itemid-".$_product->getId() ?>">
                                <span class="label"><strong><?= __('Qty Available') ?> </strong></span>
                                <div class="value"><?php echo $qtyAvailable['qty'] ?></div>
                            </div>
        <?php endif; ?>
                        <?php if ($availQtyStatus == 1): ?>
                			<div class="details-qty addeditemqty" id="<?php echo "itemid-".$_product->getId() ?>">
                			<strong class="config-message"><?php echo  __($message) ?></strong>
                			</div>
    <?php endif; ?>
                
    <?php $i++; ?>
    </div>
<?php endforeach; ?>
</div>
<?php endif; ?>