<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Grid $block */
$customerAddressView = $block->getData('customer_address');
?>
<?php
$_helper = $this->helper('Altitude\SX\Helper\Data');
?>
<div class="block block-addresses-list">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Additional Address Entries')) ?></strong></div>
    <div class="block-content">
        <?= $block->escapeHtml(__('If you have a credit account with us, please contact your local sales rep or sales desk to add a new Ship To location')) ?>
    </div>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()) : ?>

            <div class="table-wrapper additional-addresses">
                <table class="data table table-additional-addresses-items history" id="additional-addresses-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Additional addresses')) ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col shipto"><?= $block->escapeHtml(__('Ship&nbsp;To')) ?></th>
                        <th scope="col" class="col lastname"><?= $block->escapeHtml(__('Company')) ?></th>
                        <th scope="col" class="col firstname" style="display:none;"><?= $block->escapeHtml(__('First Name')) ?></th>
                        <th scope="col" class="col lastname" style="display:none;"><?= $block->escapeHtml(__('Last Name')) ?></th>
                        <th scope="col" class="col streetaddress"><?= $block->escapeHtml(__('Street Address')) ?></th>
                        <th scope="col" class="col city"><?= $block->escapeHtml(__('City')) ?></th>
                        <th scope="col" class="col country"><?= $block->escapeHtml(__('Country')) ?></th>
                        <th scope="col" class="col state"><?= $block->escapeHtml(__('State')) ?></th>
                        <th scope="col" class="col zip"><?= $block->escapeHtml(__('Zip/Postal Code')) ?></th>
                        <th scope="col" class="col phone"><?= $block->escapeHtml(__('Phone')) ?></th>
                        <th scope="col" class="col actions"> </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($_pAddsses as $address) : ?>
                    <?php 
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $customerSession = $objectManager->create('Magento\Customer\Model\Session');
                        $customer=$customerSession->getCustomer();
                        $addressId = $address->getId();
                        $erpAddress=$addressId;
                        foreach ($customer->getAddresses() as $address1) {
                            $erp = $address1->getData("ERPAddressID");
                          
                            if ($address1->getId() == $addressId) {
                                //$address = $address1;
                                $erpAddress=$erp;
                                break;
                            }
                        }
                        
                       // $addressOBJ = $objectManager->get('\Magento\Customer\Api\AddressRepositoryInterface');
                        //$addressObject = $addressOBJ->getById($addressId);
                       // $erpAddress=$addressId;
            
                           // if (isset($addressObject)) {
                                //var_dump($addressObject);
                                //$erpAddress =$addressObject->getData("ERPAddressID") ;
                             
                           // }
                    ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('shipto')) ?>" class="col phone"><?= $block->escapeHtml($erpAddress) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('First Name')) ?>" class="col firstname"><?= $block->escapeHtml($address->getCompany()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('First Name')) ?>" class="col firstname" style="display:none;"><?= $block->escapeHtml($address->getFirstname()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Last Name')) ?>" class="col lastname" style="display:none;"><?= $block->escapeHtml($address->getLastname()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Street Address')) ?>" class="col streetaddress"><?= $block->escapeHtml($block->getStreetAddress($address)) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('City')) ?>" class="col city"><?= $block->escapeHtml($address->getCity()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Country')) ?>" class="col country"><?= $block->escapeHtml($block->getCountryByCode($address->getCountryId())) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('State')) ?>" class="col state"><?= $block->escapeHtml($address->getRegion()->getRegion()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Zip/Postal Code')) ?>" class="col zip"><?= $block->escapeHtml($address->getPostcode()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Phone')) ?>" class="col phone"><?= $block->escapeHtml($address->getTelephone()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <?php if ($_helper->isAbleToEditAddress()  ): ?>
                                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>"><span><?= $block->escapeHtml(__('Set Default')) ?></span></a>
                                    <a class="action delete" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($address->getId()) ?>"><span><?= $block->escapeHtml(__('Delete')) ?></span></a>
                                <?php else: ?>
                                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>"><span style="white-space: nowrap;"><?= $block->escapeHtml(__('Set Default')) ?></span></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php if ($block->getChildHtml('pager')) : ?>
                <div class="customer-addresses-toolbar toolbar bottom"><?= $block->getChildHtml('pager') ?></div>
            <?php endif ?>
        <?php else : ?>
            <p class="empty"><?= $block->escapeHtml(__('You have no other address entries in your address book.')) ?></p>
        <?php endif ?>
    </div>
</div>

<div class="actions-toolbar">
    <?php if ($_helper->isAbleToEditAddress()): ?>
    <div class="primary">
        <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('Add New Address')) ?></span></button>
    </div>
     <?php endif; ?>
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "td a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
