<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function() {
    
    var simpleSku = $("div[itemprop='sku']").text();
    var url= BASE_URL + "/altitudesx/index/getajax";
    var basePrice = 0;
    var formatter = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 2,
    });
    console.log('checking price//...');
    $.ajax({
        url: url,
        type: "GET",
        data: {
            sku: simpleSku,
        }
    }).done(function(msg) {
        basePrice = parseFloat(msg) ;
         console.log('price=' + basePrice);
        if (basePrice>0) {
            console.log('setting price');
            basePrice = formatter.format(basePrice);
            $('.product-info-price .price-box .price-container .price').html(basePrice);
            $('div.price-final_price .normal-price .price-container .price-wrapper .price:first').html(basePrice);
            $('.sticky-price .price-box .price-container .price').html(basePrice);
            $('.product-info-price .price-box .price-container .price-wrapper:first ').data('priceAmount',basePrice)
            console.log('done setting price');
        }
        
        $('.price').contents().filter(function() {
                return this.nodeType == 3
            }).each(function(){
                this.textContent = this.textContent.replace('CA$0.00',__('Select option to see price'));
                this.textContent = this.textContent.replace('$0.00',__('Select option to see price'));
            });
    });
});
}

);
</script>
